---
- hosts: node1
  tasks:
    - name: Find postfix config files
      command: find /etc/postfix -type f -name *.cf
      register: output
    - name: Debug output
      debug:
        var: output
    - name: List postfix config files
      debug:
        var: output.stdout_lines
      loop: "{{ output }}"
