---
- hosts: node1
  tasks:
    - name: Find postfix config files
      command: find /etc/postfix -type f -name *.cf
      register: output
    - name: List postfix config files
      debug:
        var: output.stdout_lines
    - name: Backup postfix config files
      command: "cp {{ item }} {{ item }}.bkp"
      with_items: "{{ output.stdout_lines }}"
      become: yes
